import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>LinkedIn OAuth 2.0 test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          LinkedIn OAuth 2.0 test
        </h1>
        <Link href={"https://www.linkedin.com/oauth/v2/authorization?response_type=code&client_id=" + process.env.NEXT_PUBLIC_LINKEDIN_CLIENT_ID + "&redirect_uri=http://localhost:3000/api/linkedin/callback&scope=r_emailaddress"} legacyBehavior> 
          <div className = {styles.card}>
              Login with LinkedIn  
          </div>
        </Link>        
      </main>

      <footer className={styles.footer}>
        <p>Gianfranco Bazzani UOC Ciberseguretat i Privadesa FonCib PRAC1</p>
      </footer>
    </div>
  )
}
